"""comments for dops

Revision ID: 5c73bd40eba0
Revises: a75e33d0d646
Create Date: 2025-07-28 23:46:32.745770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c73bd40eba0'
down_revision = 'a75e33d0d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dops_comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dops_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dops_id'], ['dops.dops_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_table('dops_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dops_comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dops_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dops_id'], ['dops.dops_id'], name=op.f('dops_comment_dops_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], name=op.f('dops_comment_user_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('dops_comment_pkey'))
    )
    op.drop_table('dops_comments')
    # ### end Alembic commands ###
