"""change

Revision ID: 75394bb640cb
Revises: b96a78a07d39
Create Date: 2025-08-14 09:07:21.589618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75394bb640cb'
down_revision = 'b96a78a07d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_column('final_status')

    # ### end Alembic commands ###
