"""comments for dops

Revision ID: a75e33d0d646
Revises: d6000c37a681
Create Date: 2025-07-28 23:45:15.355135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75e33d0d646'
down_revision = 'd6000c37a681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_dops_id_fkey'), type_='foreignkey')
        batch_op.drop_column('dops_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dops_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('comments_dops_id_fkey'), 'dops', ['dops_id'], ['dops_id'])

    # ### end Alembic commands ###
