"""back to defaults

Revision ID: b96a78a07d39
Revises: f4aa5cdae351
Create Date: 2025-08-07 09:33:30.569381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b96a78a07d39'
down_revision = 'f4aa5cdae351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['gooners.user_id'], name=op.f('followers_followed_id_fkey')),
    sa.ForeignKeyConstraint(['follower_id'], ['gooners.user_id'], name=op.f('followers_follower_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('followers_pkey'))
    )
    # ### end Alembic commands ###
