"""Private accounts + followers table

Revision ID: f4aa5cdae351
Revises: 5c73bd40eba0
Create Date: 2025-08-07 09:28:40.114301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aa5cdae351'
down_revision = '5c73bd40eba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['gooners.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    op.drop_table('followers')
    # ### end Alembic commands ###
