"""Initial migration

Revision ID: 96d2606f16ca
Revises: 
Create Date: 2025-10-22 13:13:54.625705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d2606f16ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gooners',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('DOB', sa.String(length=100), nullable=True),
    sa.Column('dp', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dops',
    sa.Column('dops_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dops', sa.String(length=200), nullable=True),
    sa.Column('dops_caption', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('dops_id')
    )
    op.create_table('followers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.Column('final_status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['gooners.user_id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post', sa.String(length=200), nullable=True),
    sa.Column('post_caption', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['gooners.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.String(length=300), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('dops_comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dops_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dops_id'], ['dops.dops_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dops_comments')
    op.drop_table('comments')
    op.drop_table('requests')
    op.drop_table('posts')
    op.drop_table('followers')
    op.drop_table('dops')
    op.drop_table('gooners')
    # ### end Alembic commands ###
